[package]
name = "badpiggies-cryptor"
version = "0.1.0"
edition = "2021"
authors = ["ed1th"]
description = "Bad Piggies user data cryptor"
categories = ["command-line-utilities"]
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = { version = "0.8.2" }
sha1 = { version = "0.10.5" }
cbc = { version = "0.1.2", features = ["std"] }
pbkdf2 = { version = "0.12.1", features = ["hmac"]}
clap = { version = "4.1.9", features = ["derive"] }

